"""Control-run lifecycle classification generated from the producer contract."""

# Generated by scripts/generate_control_run_lifecycle.py. Do not edit by hand.

from __future__ import annotations

from types import MappingProxyType
from typing import TypedDict


CONTROL_RUN_CONTRACT_VERSION = "control-run-v1"


class ControlRunStateClassification(TypedDict):
    active: bool
    terminal: bool
    resumable: bool
    cancellable: bool


CONTROL_RUN_STATE_CLASSIFICATION: MappingProxyType[
    str, ControlRunStateClassification
] = MappingProxyType(
    {
        "starting": {
            "active": True,
            "terminal": False,
            "resumable": False,
            "cancellable": True,
        },
        "queued": {
            "active": True,
            "terminal": False,
            "resumable": False,
            "cancellable": True,
        },
        "waiting": {
            "active": True,
            "terminal": False,
            "resumable": False,
            "cancellable": True,
        },
        "running": {
            "active": True,
            "terminal": False,
            "resumable": False,
            "cancellable": True,
        },
        "approval_pending": {
            "active": True,
            "terminal": False,
            "resumable": False,
            "cancellable": True,
        },
        "completed": {
            "active": False,
            "terminal": True,
            "resumable": False,
            "cancellable": False,
        },
        "budget_limited": {
            "active": False,
            "terminal": True,
            "resumable": False,
            "cancellable": False,
        },
        "failed": {
            "active": False,
            "terminal": True,
            "resumable": True,
            "cancellable": False,
        },
        "interrupted": {
            "active": False,
            "terminal": True,
            "resumable": True,
            "cancellable": False,
        },
        "cancelled": {
            "active": False,
            "terminal": True,
            "resumable": True,
            "cancellable": False,
        },
    }
)


def _states_where(classifier: str) -> frozenset[str]:
    return frozenset(
        state
        for state, classification in CONTROL_RUN_STATE_CLASSIFICATION.items()
        if classification[classifier]
    )


CONTROL_RUN_STATES = frozenset(CONTROL_RUN_STATE_CLASSIFICATION)
CONTROL_ACTIVE_RUN_STATES = _states_where("active")
CONTROL_TERMINAL_RUN_STATES = _states_where("terminal")
CONTROL_RESUMABLE_RUN_STATES = _states_where("resumable")
CONTROL_CANCELLABLE_RUN_STATES = _states_where("cancellable")
CONTROL_CHAT_MESSAGEABLE_RUN_STATES = frozenset(
    {
        "starting",
        "queued",
        "waiting",
        "running",
        "approval_pending",
        "completed",
    }
)
CONTROL_CHAT_TOKEN_FORGET_STATES = (
    CONTROL_TERMINAL_RUN_STATES - CONTROL_CHAT_MESSAGEABLE_RUN_STATES
)


def is_control_run_state(value: object) -> bool:
    return isinstance(value, str) and value in CONTROL_RUN_STATES


def is_control_run_active_state(value: object) -> bool:
    return isinstance(value, str) and value in CONTROL_ACTIVE_RUN_STATES


def is_control_run_terminal_state(value: object) -> bool:
    return isinstance(value, str) and value in CONTROL_TERMINAL_RUN_STATES


def is_control_run_resumable_state(value: object) -> bool:
    return isinstance(value, str) and value in CONTROL_RESUMABLE_RUN_STATES


def is_control_run_cancellable_state(value: object) -> bool:
    return isinstance(value, str) and value in CONTROL_CANCELLABLE_RUN_STATES


def is_control_chat_messageable_state(value: object) -> bool:
    return isinstance(value, str) and value in CONTROL_CHAT_MESSAGEABLE_RUN_STATES


def should_forget_control_chat_token(value: object) -> bool:
    return isinstance(value, str) and value in CONTROL_CHAT_TOKEN_FORGET_STATES
